# Generated by Django 4.0.6 on 2022-11-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_email_contact_email_rename_name_contact_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='desc',
            field=models.TextField(max_length=1678795, null=True),
        ),
    ]
